import org.apache.commons.dbcp2.BasicDataSource
import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate
import javax.swing.JOptionPane

fun main() {
    var quantidade = 0
    val dataSource = BasicDataSource();
    dataSource.driverClassName = "org.h2.Driver"
    dataSource.url = "jdbc:h2:mem:sptech"
    dataSource.username = "sa"
    dataSource.password = ""

    val jdbcTemplate = JdbcTemplate(dataSource)

    jdbcTemplate.execute("""
        create table pizza (
           codigo INT GENERATED BY DEFAULT AS IDENTITY primary key,
           sabor varchar(40) not null,
           preco FlOAT,
           quantidade INT
        )
    """.trimIndent()
    )
    while (true){
        val cadastro = JOptionPane.showInputDialog(null,"Quer cadastrar uma nova pizza? s para sim ou qualquer coisa para não")
        if (cadastro == "s") {
            val pizza1 = Pizza()
            pizza1.sabor = JOptionPane.showInputDialog(null, "Qual o sabor da pizza?🎉")
            pizza1.preco = JOptionPane.showInputDialog(null, "Qual o preco ($) da pizza?").toDouble()
            pizza1.quantidade = JOptionPane.showInputDialog(null, "Quantas pizzas vão ser?").toInt()


            val linhasAfetadas = jdbcTemplate.update("""
        insert into pizza (sabor, preco, quantidade) values
        ('${pizza1.sabor}', ${pizza1.preco}, ${pizza1.quantidade})
    """.trimIndent())
            println("$linhasAfetadas linha inserida")
            quantidade++
        } else {
            break
        }
    }

    while (true){
        val vender = JOptionPane.showInputDialog(null, "Qual pizza quer vender? Digite de 1 a ${quantidade}").toInt()
        if(vender in (quantidade)..0){
            JOptionPane.showMessageDialog(null, "Valor Inválido!")
        } else {
    val disponiveis = jdbcTemplate.queryForList(
        "select * from pizza where codigo = ${vender}",
        BeanPropertyRowMapper(Pizza::class.java)
    )
            jdbcTemplate.update("""
        UPDATE pizza set quantidade = ${disponiveis - 1} where codigo = ${vender};
    """.trimIndent())
                 val sabor_selecionado = jdbcTemplate.update("""
        select sabor from pizza where codigo = ${vender};
    """.trimIndent())
                JOptionPane.showMessageDialog(null, "Quantidade da pizza de ${sabor_selecionado} atualizada para ${disponiveis - 1}")
            }
        }
    }

