import org.apache.commons.dbcp2.BasicDataSource
import org.springframework.jdbc.core.JdbcTemplate
class ConexaoBd {
    var jdbcTemplate: JdbcTemplate? = null
        get(){
            if(field == null){
                val dataSource = BasicDataSource()
                dataSource.driverClassName = "org.h2.Driver"
                dataSource.url = "jdbc:h2:mem:sptech"
                dataSource.username = "sa"
                dataSource.password = ""
                val novoJdbcTemplate = JdbcTemplate(dataSource)
                field = novoJdbcTemplate
            }
            return field
        }
    fun Tabela(){
        jdbcTemplate!!.execute("""
            create table if not exists Musica(
            id Int GENERATED BY DEFAULT AS IDENTITY primary key, 
            titulo varchar(30), 
            artista varchar(30), 
            dataCriacao date)
            """)
    }
}
